version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: kueue-db
    volumes:
      - kueue-pgdata:/var/lib/postgresql/data
      - ./../config/db/:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_PASSWORD: ${PG_PASS}
    ports:
      - $PG_PORT:5432

volumes:
  kueue-pgdata:
